### ISSUE TITLE
ts-transform-paths doesn't work with module set to commonjs

### ISSUE THREAD

**Issue by filenwind** [zerkalica/zerollup#1]
As title, set module as commonjs in compiler options, it won't replace path in require.

If I change module to esnext, it work great.

Can you take a look? Or I missing something?

Thank you!

**Comment by zerkalica** [comment]
Yes, require not supported, do you now any ts transform examples with correct require detect?

**Comment by zerkalica** [comment]
Try 1.2.0

**Comment by filenwind** [comment]
Hi, I tried, not working either.

.d.ts work fine, but .js is not.

This is the sample [repo](https://github.com/filenwind/ts-transform-paths-issue).

Thanks for your help!

**Comment by zerkalica** [comment]
Check 1.2.2

**Comment by filenwind** [comment]
It's work now! Thanks!
