### ISSUE TITLE
Problems when using ttsc -w

### ISSUE THREAD

**Issue by Mairu** [zerkalica/zerollup#12]
When using ttsc with the configured transformer in watch mode the initial build is successful. When changing a file that is imported using a transformed path, the file importing this file will be rebuild without changing import path.

I created a repository to reproduce this issue: https://github.com/Mairu/ts-transform-paths-watch-issue

Thanks for the transformer by the way.

**Comment by zerkalica** [comment]
Check 1.7.1

**Comment by Mairu** [comment]
Works! Thank you very much.
