### ISSUE TITLE
`@zerollup/ts-transform-paths@1.7.6` not working with `compilerOptions.skipLibCheck = true`

### ISSUE THREAD

**Issue by leftstick** [zerkalica/zerollup#19]
Once i have both `compilerOptions.skipLibCheck: true` and `"sourceMap": true ` in `tsconfig.json`, `paths` would not de-mappinged in generated declarations `.d.ts` files.

This is really weird.

I am using `@zerollup/ts-transform-paths@1.7.6` with `rollup-plugin-typescript2` by the way

**Comment by zerkalica** [comment]
Can you provide example or tsconfig? I tested 1.7.6 with `skipLibCheck: true` in my demo https://github.com/zerkalica/zerollup-test-18 and in https://github.com/MichalLytek/type-graphql/tree/vNext

Update. I added rollup config: https://github.com/zerkalica/zerollup-test-18/tree/rollup, rewrites still working.

**Comment by leftstick** [comment]
@zerkalica  i cannot reproduce it now with a minimal example, that might be caused by something else. I will close this issue for now. Thanks for your help

**Comment by zerkalica** [comment]
Thanks, reopen it, if reproduce bug anywhere.
