### ISSUE TITLE
[ts-transform-paths] cannot map to package.json at root folder

### ISSUE THREAD

**Issue by opensas** [zerkalica/zerollup#21]
I have the following setup in my tsconfig.json

```javascript
    "baseUrl": "./",
    "paths": {
      "@project/*": ["./*"],
      "*": ["./src/*"],
      "@*": ["./src/*"],
    },
    //"plugins": [
    //  { "transform": "ts-transformer-imports" }
    //],

    "plugins": [
       { "transform": "@zerollup/ts-transform-paths", "exclude": ["*"] }
    ],
```

And in my start.ts

```typescript
import { name as appName } from '@project/package.json'
```

After compiling with ttsc I get this in my start.js

```javascript
[...]
Object.defineProperty(exports, "__esModule", { value: true });
var package_json_1 = require("@project/package.json");
var app_1 = __importDefault(require("./app"));
[...]
```

It looks like it cant map the `@project/package.json` reference and just leaves it like this, without any error or warning...

With `ts-transformer-imports` (commented in the tsconfig file) and with tsconfig-paths it works ok, and I get package.json mapped like this:

```javascript
Object.defineProperty(exports, "__esModule", { value: true });
var package_json_1 = require("../package.json");
var app_1 = __importDefault(require("./app"));
var config_1 = __importStar(require("./lib/config/config"));
```

Also tried with this configuration in tsconfig, same result:

```javascript
    "baseUrl": "./src",
    "paths": {
      "@project/*": ["./../*"],
      //"@project/package.json": ["./../package.json"],
      "@*": ["./*"],
```

I'm not sure if the problem is with having a reference to something outside of my baseUrl or with references to .json files

thanks a lot

**Comment by zerkalica** [comment]
try 1.7.8

**Comment by opensas** [comment]
I can confirm that with version 1.7.8 everything seems to work ok.

No I can run ts-node with `ts-node -C ttypescript src/start.ts` and it works too

You've responded with a new version solving the issue in just a couple of hours!!!

FLOSS really rocks, congratulations on the great job you are doing
