### ISSUE TITLE
[ts-transform-paths] CSS import path is not transformed

### ISSUE THREAD

**Issue by blvdmitry** [zerkalica/zerollup#25]
Hey, I guess I've got quite an exotic setup. it's a monorepo and I've got @zerollup/ts-transform-paths installed and added into my root tsconfig.json:

```
{
  "compilerOptions": {
    "sourceMap": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "target": "esnext",
    "lib": ["es2017", "dom"],
    "jsx": "react",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "declaration": true,
    "baseUrl": "src",
    "outDir": "dist",
    "resolveJsonModule": true
  },
  "exclude": [
    "node_modules",
    "packages/**/node_modules"
  ],
  "plugins": [{ "transform": "@zerollup/ts-transform-paths" }],
  "paths": { "*": ["*"] }
}
```

Then I've got a package in the monorepo that extends this config just to update some properties:
```
{
  "extends": "../../tsconfig",
  "compilerOptions": {
    "outDir": "dist",
    "baseUrl": "src",
    "rootDir": "src",
    "target": "es5",
    "module": "commonjs"
  },
  "exclude": [
    "node_modules",
    "dist"
  ]
}
```

In the whole project I've got two types of files I have to compile - standalone files that I compile with `ttypescript` and UI bundles where I use `ts-loader`.

In both cases ts imports work just fine but fail for css file imports:
```
import React from 'react';
import ReactDOM from 'react-dom';
import 'styles/normalize.css';
import App from 'containers/App';

ReactDOM.render(<App />, document.getElementById('root'));
```

transforms imports to
```
require("styles/normalize.css");
var ImportMenu_1 = __importDefault(require("../containers/ImportMenu"));
```

Do you think this is an issue in the plugin or am I missing something there?

**Comment by zerkalica** [comment]
Check 1.7.12

**Comment by blvdmitry** [comment]
Thanks for the quick response!
Unfortunately, I still get the same output with 1.7.12
Two potential differences from the test might be that I'm using "paths": { "*": ["*"] } and that I have custom.d.ts:

```
declare module '*.svg' {
  const content: string;
  export default content;
}

declare module '*.css' {
  const content: Record<string, string>;
  export default content;
}
```

The latter one seems like it might be causing this issue since svg transforms don't work as well

**Comment by zerkalica** [comment]
Can you provide demo example, pls?
