### ISSUE TITLE
[ts-transform-paths] import from '.' is improperly transformed, when using absolute imports

### ISSUE THREAD

**Issue by falkenhawk** [zerkalica/zerollup#28]
```javascript
// tsconfig.json
{
  "compilerOptions": {
    "baseUrl": "src"
    "plugins": [{ "transform": "@zerollup/ts-transform-paths" }],
    "paths": { "*": ["*"] },
  }
}

// src/module/testing/help.ts
import { abc } from '.';

// src/module/testing/index.ts
export function abc();
```

results in:
```javascript
// build/src/module/testing/help.js
const _1 = require("../../../..");
// instead of
const _1 = require(".");
```

**Comment by falkenhawk** [comment]
maybe `"*": ["*"]` in `paths` shouldn't be required for the absolute imports to work? (as per https://github.com/zerkalica/zerollup/blob/master/packages/ts-transform-paths/README.md#external-packages - but it's required now, otherwise absolute imports are not transformed)

Because such setting breaks such imports from '.' also in non-compiled typescript... - they now point to root dir instead of the current relative dir...

**Comment by zerkalica** [comment]
Try 1.7.13

**Comment by falkenhawk** [comment]
@zerkalica Absolute imports work now, without `"paths": { "*": ["*"] }` in `tsconfig.json`, thanks!

However, `import { abc } from '.'` (just the dot) still fails (resolves to baseUrl), whereas `from './'` and `from './index'` work fine.

Also note, that directory separator in paths are casted to `\\` now (I'm on windows), but only for absolute imports, e.g.:
```javascript
const ow_pubsub_1 = require("..\\..\\..\\ow-pubsub"); // import { pubsub } from 'modules/ow-pubsub'
// the path above could be simply "../../../ow-pubsub", also on windows

const index_1 = require("./index"); // import { abc } from './index' works, but
const _1 = require("..\\..\\..\\.."); // import { abc } from '.' still resolves to baseUrl folder
```

**Comment by falkenhawk** [comment]
@zerkalica "import from '.'" also does not work on linux:
```javascript
const _1 = require("../../../..");
```
expected
```javascript
const _1 = require(".");
```

**Comment by zerkalica** [comment]
Try 1.7.15

**Comment by falkenhawk** [comment]
@zerkalica I can confirm 1.7.15 works fine. Thank you!
