### ISSUE TITLE
Wrong output path with similar module name

### ISSUE THREAD

**Issue by filenwind** [zerkalica/zerollup#3]
import similar module will cause wrong output path

This is example [repository](https://github.com/filenwind/ts-transform-paths-issue). 

`npm run build:ttsc`
`npm run start`

tsconfig:
```json
{
  "compilerOptions": {
    "paths": {
      "app/*": ["src/app/*"],
      "app": ["src/app/index"]
    },
  }
}
```
code:
```js
import app from 'app';
import appRootPath from 'app-root-path';
import application from 'application';

console.log('app', app);
console.log('appRootPath', appRootPath);
console.log('application', application);
```

After compiler, appRootPath, application will import from app path.

**Comment by zerkalica** [comment]
fix works for you?
