### ISSUE TITLE
Support for project references in ts-transform-paths 

### ISSUE THREAD

**Issue by purplemana** [zerkalica/zerollup#5]
I have logged an [issue](https://github.com/cevek/ttypescript/issues/28) with ttypescript repo in case this needs to be fixed there.

Basically in a mono-repo setup where there are TypeScript 3.0 project-references, when you build a package with `tsc -b`, TypeScript also builds all the dependency packages in the right order before building the current package. However, with `ttsc -b` and `ts-transform-paths` only the current package paths are being transformed, even though all the dependency packages are being built.

Wanted to know if this can be fixed in the transform's code or it needs an enhancement in `ttypescript`?

Cheers.

**Comment by purplemana** [comment]
[Turned out](https://github.com/cevek/ttypescript/issues/28#issuecomment-435589566) I had the `plugins` added to the global node of my `tsconfig`. After moving it inside `compilerOptions` this works as advertised.

**Comment by zerkalica** [comment]
Good =)

**Comment by MichalLytek** [comment]
@zerkalica 
I'm not sure if I should open a separate issue but this doesn't work well for me.
I have setup `plugins` in `compilerOptions` only in one package, not the global/root `tsconfig`.

However my output `*.js` files are not transformed properly (`var greet_1 = require("@src/greet");`) and the declarations are broken (`export { default as greet } from ;`). Original `index.ts` is `export { default as greet } from "@src/greet";` 😕 

If I execute `ttsc` in normal mode `composite: false` in the package folder, it transpiles properly.

**Comment by zerkalica** [comment]
Can you provide minimal example for this bug?

**Comment by MichalLytek** [comment]
@zerkalica 
It's really weird, I can run it with no problem on this:
https://github.com/RyanCavanaugh/learn-a

But not in my repo which is 1:1 the same TS config, just a prettier/eslint config and tsconfig on root repo, not in packages subfolder. Can I create a private repo and add you to it? 😉

**Comment by zerkalica** [comment]
@19majkel94 I clone you repository, but can't reproduce, `core/lib/index.d.ts` has relative path to greet. I think it was fixed in #12, try version 1.7.1

**Comment by MichalLytek** [comment]
It makes sense 😉 Thanks!

I've ended up in refactoring the `RyanCavanaugh/learn-a` example and it's working now without any problems 🎉
