### ISSUE TITLE
Building a single package

### ISSUE THREAD

**Issue by marcus-sa** [zerkalica/zerollup#9]
After looking at your https://github.com/zerkalica/zerollup-demo mono repository demo, I noticed that you could build all the packages using `rollup -c node:@zerollup/rollup-preset-ts`, but how would I go by with only building a single package?

Thanks a lot for this btw!

**Comment by marcus-sa** [comment]
Solved it by simply adding a the same build script in the corresponding package :)

**Comment by zerkalica** [comment]
You can use BUILD_PKG environment variable and pass one or multiple project names.
``` BUILD_PKG=lib1,lib2 npm run build ```

https://github.com/zerkalica/zerollup/blob/master/packages/rollup-preset-ts/src/index.ts#L46
